language: node_js
node_js:
- 8
os:
- osx
- linux
sudo: required
dist: trusty
osx_image: xcode9
compiler:
- clang
addons:
  apt:
    packages:
    - icnsutils
    - graphicsmagick
    - xz-utils
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  rvm install 2.2.0;
  ruby --version;
  gem --version;
  gem install fpm;
  fi
- node --version
- yarn --version
install:
- yarn
- yarn list

script:
- yarn run test
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  openssl aes-256-cbc -K $encrypted_fc666da9e2f5_key
  -iv $encrypted_fc666da9e2f5_iv
  -in .travis.env.enc
  -out .travis.env
  -d;
  source .travis.env;
  yarn run snyk;
  yarn run mac;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  yarn run linux;
  fi
