language: c
os:
  - osx
env:
  global:
    - NODE_VERSION=5
cache:
  directories:
    - node_modules
    - app/node_modules
    - .nvm
    - $HOME/.electron
    - $HOME/.npm
before_install:
  - if [ ! ./.nvm ]; then git clone https://github.com/creationix/nvm.git ./.nvm; fi
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
install:
  - npm prune
  - npm install
script:
  - make test
  - npm run dist
