language: node_js
node_js:
- 12
os:
- osx
- linux
sudo: required
dist: bionic
osx_image: xcode11
compiler:
- clang
addons:
  apt:
    packages:
    - libopenjp2-tools
cache:
  npm: false
before_install:
- openssl aes-256-cbc -K $encrypted_fc666da9e2f5_key -iv $encrypted_fc666da9e2f5_iv
  -in .travis.env.enc -out .travis.env -d; source .travis.env;
- node --version
- yarn --version
install:
- yarn
before_script:
- yarn list
script:
- "./scripts/travis.sh"
deploy:
  provider: snap
  snap: dist/*.snap
  channel: edge
  skip_cleanup: true
  on:
    condition: $TRAVIS_OS_NAME = "linux"