language: cpp
os:
- osx
- linux
sudo: required
dist: trusty
osx_image: xcode8 # currently xcode8.1+ doesn't support electron-builder macOS code-signing (https://github.com/electron-userland/electron-builder/issues/820#issuecomment-256728535)
compiler:
- clang
env:
  global:
  - NODE_VERSION=5
addons:
  apt:
    packages:
    - icnsutils
    - graphicsmagick
    - xz-utils
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then openssl aes-256-cbc -K $encrypted_fc666da9e2f5_key
  -iv $encrypted_fc666da9e2f5_iv -in .travis.env.enc -out .travis.env -d; source .travis.env;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rvm install 2.2.0; ruby --version; gem
  --version; gem install fpm; fi
- if [ ! -f ./.nvm/nvm.sh ]; then git clone https://github.com/creationix/nvm.git
  ./.nvm; fi
- source ./.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use --delete-prefix $NODE_VERSION
- npm install -g npm
- node --version
- npm --version
install:
- npm prune
- npm install
script:
- make ci
