language: cpp
os:
  - osx
#  - linux
compiler:
  - clang
env:
  global:
    - NODE_VERSION=5
addons:
  apt:
    packages:
      - icnsutils
cache:
  directories:
    - node_modules
    - app/node_modules
    - .nvm
    - $HOME/.electron
    - $HOME/.npm
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gem install fpm; fi
  - if [ ! -f ./.nvm/nvm.sh ]; then git clone https://github.com/creationix/nvm.git ./.nvm; fi
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
install:
  - npm prune
  - npm install
script:
  - make ci
