version: 0.1.1-{build}
platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
    secure: lAoTVd9zu2MCJs2+NplDMegxezyoXTU5HK4OYpQQrJCOX9Mq542OcrqZlQa61qxn

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm prune
  - npm update

build_script:
  - node --version
  - npm --version
  - npm run dist

test: off
