version: build{build}
platform:
  - x64
os: Previous Visual Studio 2015

environment:
  GYP_MSVS_VERSION: 2015
  GH_TOKEN:
    secure: lAoTVd9zu2MCJs2+NplDMegxezyoXTU5HK4OYpQQrJCOX9Mq542OcrqZlQa61qxn
  
  AZURE_KEY_VAULT_URL:
    secure: GYdBKr1bwel6q0nE0k/K74HvIIHdp8EkqQOURzYjcm22na3pz4lx73Prqt163969
  AZURE_KEY_CLIENT_ID:
    secure: PaHBZKGDgPBnTuKIqinapp2NL4KW/Z3pDKwDCkxNBmuzP56WTfKOM+Vy3obmj+AS
  AZURE_KEY_CLIENT_SECRET:
    secure: 2LoLviUUNk5knt3Sq5NIbCvKNhx2Szs93pEyCgYErLJFPf2pgxgO1CWeDHF0U2VU
  AZURE_KEY_VAULT_CERTIFICATE:
    secure: VDfW/dOV7r5qSsjeafl7NpD/hnyHJQL/NZmuAub59No5Bu02oPIhDO23zqs7To2z

  SENTRY_DSN: https://33cd6b2300f14ece9b7e6b6234a0b5fd:ee2f464c5562430da9a8fa08a945316a@sentry.io/224616

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - dotnet tool install --global AzureSignTool --version 2.0.17
  - git reset --hard HEAD
  - node --version
  - yarn --version
  - python --version
  - yarn
  - yarn list
  - yarn run test

build_script:
  - yarn run win
