name: Build

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install linux deps
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install --no-install-recommends -y libopenjp2-tools

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        # Only install Snapcraft on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        with:
          # Log in to Snap Store
          snapcraft_token: ${{ secrets.snapcraft_token }}

      - name: Install azuresigntool
        if: startsWith(matrix.os, 'windows')
        run: |
          dotnet tool install --global AzureSignTool --version 2.0.17

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          # Windows code signing azure key vault
          AZURE_KEY_VAULT_URL: ${{ secrets.azure_key_vault_url }}
          AZURE_KEY_CLIENT_ID: ${{ secrets.azure_key_client_id }}
          AZURE_KEY_CLIENT_SECRET: ${{ secrets.azure_key_client_secret }}
          AZURE_KEY_VAULT_CERTIFICATE: ${{ secrets.azure_key_vault_certificate }}
          # macOS code signing certificate
          CSC_LINK: ${{ secrets.mac_csc_link }}
          CSC_KEY_PASSWORD: ${{ secrets.mac_csc_key_password }}
          # macOS notarization API key
          APPLEID: ${{ secrets.appleid }}
          APPLEIDPASS: ${{ secrets.appleidpass }}
