name: Test

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Test
        if: startsWith(matrix.os, 'macos')
        run: |
          yarn run test
          yarn run snyk
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
